config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  get "produtos/busca", to:"produtos#busca", as: :busca_produto
  resources :produtos, only:[:new, :create, :destroy,:edit,:update]
  root to:"produtos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :departamento
  
  validates :preco, presence: true
  validates :nome, length: {minimum: 4}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: %i[ show edit update destroy ]

  # GET /departamentos or /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1 or /departamentos/1.json
  def show
    @produtos_por_departamento = Produto.where("departamento_id = ?",params[:id])
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos or /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to departamento_url(@departamento), notice: "Departamento was successfully created." }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1 or /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to departamento_url(@departamento), notice: "Departamento was successfully updated." }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1 or /departamentos/1.json
  def destroy
    @departamento.destroy

    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: "Departamento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  before_action :set_produto, only:[:edit,:update,:destroy]

  def index
    @produtos = Produto.order(nome: :asc)
    @produto_com_desconto = Produto.order(:preco).limit 1
  end

  def new
    @produto = Produto.new
    @departamentos = Departamento.all
  end

  def create
    @produto = Produto.new produto_params
    if @produto.save
      flash[:notice] = "Produto salvo com sucesso!"
      redirect_to root_url
    else
      renderiza :new
    end
  end

  def edit
    
    renderiza :edit
  end

  def update
        
    if @produto.update produto_params
      flash[:notice] = "Produto atualizado com sucesso!"
      redirect_to root_url
    else
      renderiza :edit
    end
  end

  def destroy
    @produto.destroy 
    redirect_to root_url
  end

  def busca
    nome = params[:nome]
    @produtos = Produto.where "nome like?", "%#{nome}%"
  end

  private

  def produto_params
    params.require(:produto).permit(:nome,:descricao,:preco,:quantidade,:departamento_id)
  end

  def set_produto
    @produto = Produto.find(params[:id])
  end

  def renderiza(view)
    @departamentos = Departamento.all 
    render view
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_departamento.html.erb
<div id="<%= dom_id departamento %>">
  <p>
    <strong>Nome:</strong>
    <%= departamento.nome %>
  </p>

</div>

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento) do |form| %>
  <% if departamento.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
        <% departamento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing departamento</h1>

<%= render "form", departamento: @departamento %>

<br>

<div>
  <%= link_to "Show this departamento", @departamento %> |
  <%= link_to "Back to departamentos", departamentos_path %>
</div>

app/views/departamentos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Departamentos</h1>

<div id="departamentos">
  <table class="table table-bordered table-hover mt-100">
      <thead>
        <tr>
          <td>Nome</td>
          
          <td colspan="3"></td>
        </tr>
      </thead>
      <tbody>
        <%@departamentos.each do |departamento|%>
          <tr>
            <td>
              <%=departamento.nome%>
            </td>
            <td>
              <%=link_to "Ver produtos", departamento, class:"btn btn-info"%>
            </td>
            <td>
              <%=link_to "Editar", edit_departamento_path(departamento) , class:"btn btn-warning"%>
            </td>
             <td>
              <%= button_to "Remover", departamento, method: :delete, class:"btn btn-danger", data: {confirm: "Tem certeza que deseja deletar eeste produto?"} %>
            </td>
          </tr>
          <%end%>
      </tbody>
    </table>
</div>

<%= link_to "Criar novo departamento", new_departamento_path,class:"btn btn-dark" %>

app/views/departamentos/new.html.erb
<h1>New departamento</h1>

<%= render "form", departamento: @departamento %>

<br>

<div>
  <%= link_to "Back to departamentos", departamentos_path %>
</div>

app/views/departamentos/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="m-8 container " >
    <table class="table table-bordered table-hover mt-100">
      <thead>
        <tr>
          <td>Nome</td>
          <td>Descrição</td>
          <td>Departamento</td>
          <td>Preço</td>
          <td>Quantidade</td>
          <td colspan="2"></td>
        </tr>
      </thead>
      <tbody>
       
        <%= render @produtos_por_departamento%>
       
      </tbody>
    </table>
</div>

<div>
  <%= link_to "Editar departamento", edit_departamento_path(@departamento) ,class:"btn btn-warning"%> |
  <%= link_to "Voltar", departamentos_path,class:"btn btn-primary" %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loja</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/produtos/new">Novo produto</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/departamentos">Departamentos</a>
          </li>
        </ul>
        <div class="form-group ">
        <%= form_tag busca_produto_path,method: :get, class:"navbar-form d-flex" do%> 
            <%= text_field_tag :nome,@nome,class:"form-control"%>
            <%= button_to "Buscar",nil,class:"btn btn-primary ml-8"%>
          <%end%>
        </div>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/produtos/_form.html.erb
 <% @produto.errors.full_messages.each do |msg|%>
    <div class="alert alert-danger">
      <%= msg%>
    </div>
 <% end %>

  <%= form_for @produto,data:{turbo: false} do |form|%>
    <div class="row">
      <div class="col-sm-8">
        <div class="form-group">
          <%= form.label :nome%>
          <%= form.text_field :nome, class:"form-control"%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-8">
        <div class="form-group">
          <%= form.label :descricao%>
          <%= form.text_area :descricao, class:"form-control",rows:4%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2">
        <div class="form-group">
          <%= form.label :departamento%>
          <%= form.collection_select :departamento_id,@departamentos,:id,:nome,{},class:"form-control"%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2">
        <div class="form-group">
          <%= form.label :preco%>
          <%= form.number_field :preco, class:"form-control",step:0.01%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-2">
        <div class="form-group">
          <%= form.label :quantidade%>
          <%= form.number_field :quantidade, class:"form-control"%>
        </div>
      </div>
    </div>
    <%=form.submit texto_da_acao,class:"btn btn-primary"%>
  <%end%>
</div>

app/views/produtos/_produto.html.erb
<tr>
  <td>
    <%=produto.nome%>
  </td>
  <td>
    <%=produto.descricao%>
  </td>
  <td>
    <%=produto.departamento.nome%>
  </td>
  <td>
    <%=produto.preco%>
  </td>
  <td>
    <%=produto.quantidade%>
  </td>
  <td>
    <%= link_to "Alterar", edit_produto_path(produto), class:"btn btn-primary", data: {confirm: "Tem certeza que deseja deletar eeste produto?"} %>
  </td>
   <td>
    <%= button_to "Remover", produto, method: :delete, class:"btn btn-danger", data: {confirm: "Tem certeza que deseja deletar eeste produto?"} %>
  </td>
</tr>

app/views/produtos/busca.html.erb
 <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <td>Nome</td>
          <td>Descrição</td>
          <td>Departamento</td>
          <td>Preço</td>
          <td>Quantidade</td>
          <td colspan="2"></td>
        </tr>
      </thead>
      <tbody>
        <%= render @produtos%>
      </tbody>
    </table>

app/views/produtos/edit.html.erb
<%= render partial: "form",locals:{texto_da_acao:"Atualizar"}%>

app/views/produtos/index.html.erb
<% if flash[:notice]%>
<div class="alert alert-success" role="alert">
  <%= flash[:notice]%>
</div>
<% end %>
  <div class="m-8 container " >
    <table class="table table-bordered table-hover mt-100">
      <thead>
        <tr>
          <td>Nome</td>
          <td>Descrição</td>
          <td>Departamento</td>
          <td>Preço</td>
          <td>Quantidade</td>
          <td colspan="2"></td>
        </tr>
      </thead>
      <tbody>
       
        <%= render @produtos%>
       
      </tbody>
    </table>
    <div class="alert alert-success" role="alert">
      <h2 class="alert-heading">Produto com desconto</h2>
    </div>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <td>Nome</td>
          <td>Descrição</td>
          <td>Preço</td>
          <td>Quantidade</td>
        </tr>
      </thead>
      <tbody>
        <%= render @produto_com_desconto%>
      </tbody>
    </table>

app/views/produtos/new.html.erb
<%= render partial: "form",locals:{texto_da_acao:"Criar"}%>